# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 18:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JukeBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_public', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='JukeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('link', models.URLField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.IntegerField()),
                ('down', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='stats',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jukebox.Stats'),
        ),
        migrations.AddField(
            model_name='jukebox',
            name='djs',
            field=models.ManyToManyField(related_name='subscribed_jukeboxes', to='jukebox.JukeUser'),
        ),
        migrations.AddField(
            model_name='jukebox',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jukeboxes', to='jukebox.JukeUser'),
        ),
        migrations.AddField(
            model_name='jukebox',
            name='songs',
            field=models.ManyToManyField(to='jukebox.Song'),
        ),
        migrations.AddField(
            model_name='jukebox',
            name='stats',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jukebox.Stats'),
        ),
    ]
